# AWS Config
cloud:
  aws:
    credentials:
      accessKey: AKIAYC7KPZ4GV662LLXP
      secretKey: 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
    s3:
      bucket: culetter
      folder:
        profileImage: profile_image/
        letterImage: letter_image/
        postcardImage: postcard_image/
        photocardImage: photocard_image/
        music: music/
      emotion:
        happy: happy/
        angry: angry/
        sad: sad/
        panic: panic/
    region:
      static: ap-northeast-2
    stack:
      auto: false

## EC2가 아닌 환경에서 실행시 발생하는 에러 메시지 제거
#logging:
#  level:
#    com:
#      amazonaws:
#        util:
#          EC2MetadataUtils: error
